
GET http://localhost:4000/

### 

POST http://localhost:4000/student
Content-Type: application/json

{
    "name": "sudipto",
    "email" : "sudipto354@gmail.com" ,
    "phone" : "763345544"
}
 
######
GET http://localhost:4000/students

### 


GET http://localhost:4000/student/rahul

### 


PUT http://localhost:4000/student/64ae59544910a1fa52ed22c6/
Content-Type: application/json

{
    "name" : "AvikB" 
}

###

DELETE http://localhost:4000/student/64ae57114910a1fa52ed22be/