
GET http://localhost:4000/

### 

POST http://localhost:4000/student
Content-Type: application/json

{
    "name": "sudipto",
    "email" : "sudipto354@gmail.com" ,
    "phone" : "763345544"
}
 
######
GET http://localhost:4000/students

### 


GET http://localhost:4000/student/rahul

### 


PUT http://localhost:4000/student/64ae537e90ea5449978ce969/

Content-Type: application/json

{
    "name" : "AvikBiswas" 
}



